import { PRReview } from './types';

export class ReportGenerator {
  generateMarkdown(review: PRReview): string {
    const confidenceEmoji = {
      'High': '🟢',
      'Medium': '🟡',
      'Low': '🔴'
    }[review.confidence];

    const risksList = review.risks.length > 0 
      ? review.risks.map(r => `- ⚠️ ${r}`).join('\n')
      : '- No significant risks identified';

    const suggestionsList = review.suggestions.length > 0
      ? review.suggestions.map(s => `- 💡 ${s}`).join('\n')
      : '- No suggestions at this time';

    return `## 🤖 Claude Code PR Review

### Summary
${review.summary}

### Identified Risks
${risksList}

### Improvement Suggestions
${suggestionsList}

### Confidence Score
${confidenceEmoji} **${review.confidence}**

---
*Generated by [Claude Code PR Review Agent](https://github.com/claude-builders-bounty/claude-builders-bounty)*
`;
  }

  generateConsoleOutput(review: PRReview): string {
    const lines = [
      '═'.repeat(60),
      '  CLAUDE CODE PR REVIEW',
      '═'.repeat(60),
      '',
      '📝 SUMMARY',
      review.summary,
      '',
      '⚠️  RISKS',
      ...review.risks.map(r => `  • ${r}`),
      '',
      '💡 SUGGESTIONS',
      ...review.suggestions.map(s => `  • ${s}`),
      '',
      `🎯 CONFIDENCE: ${review.confidence}`,
      '═'.repeat(60)
    ];
    return lines.join('\n');
  }
}
